# -*- coding: utf-8 -*-
"""Pic2Sketch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cwufSo3yKfIeCYjvzrFZsJwcj3ZfoeMj
"""

import cv2

import os

from flask import Flask,render_template,request,url_for,redirect,send_from_directory
from werkzeug.utils import secure_filename

UPLOAD_FOLDER = 'static/uploads/'
DOWNLOAD_FOLDER = 'static/downloads/'
ALLOWED_EXTENSIONS = {'jpg','jpeg','png','bmp'}

app = Flask(__name__,static_url_path="/static/")
DIR_PATH = os.path.dirname(os.path.abspath("__file__"))

app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER
app.config['DOWNLOAD_FOLDER'] = DOWNLOAD_FOLDER
app.config['MAX_IMAGE_SIZE'] = 10 * 1024 * 1024

def allowed_file(filename):
  return '.' in filename and filename.rsplit('.',1)[1].lower() in ALLOWED_EXTENSIONS

@app.route('/',methods=['GET','POST'])
def index():
  if request.method == 'POST':
    if 'file' not in request.files:
      print("Sorry, image not supported")
      return redirect(request.url)
    file =request.files['file']
    if file.filename == '':
      print("No file selected")
      return redirect(request.url)
    if file and allowed_file(file.filename):
      filename = secure_filename(file.filename)
      file.save(os.path.join(app.config['UPLOAD_FOLDER'],filename))
      process_file(os.path.join(app.config['UPLOAD_FOLDER'],filename),filename)
      return redirect(url_for('uploaded_file'),filename=filename)
  return render_template('index.html')

def process_file(path,filename):
  sketch(path,filename)

def dodgeV2(image,mask):
  return cv2.divide(image,255-mask, scale=256)

def sketch(path,filename):
  img = cv2.imread(path)
  img_gray = cv2.cvtcolor(img,cv2.COLOR_BGR2GRAY)
  img_gray_inv = 255 - img.gray
  img_blur = cv2.GaussianBlur(img_gray_inv, ksize=(21, 21),sigmaX=0, sigmaY=0)
  img_blend = dodgeV2(img_gray,img_blur)
  cv2.imwrite(os,path.join(app.config['DOWNLOAD_FOLDER']+filename),img_blend)

@app.route('/uploads/<filename>')
def uploaded_file(filename):
  return send_from_directory(app.config['DOWNLOAD_FOLDER'],filename,as_attachment=True)

if __name__ == '__main__':
  port = int(os.environ.get("PORT",5000))
  app.run(host='0.0.0.0',port=port)

